<?php

namespace App\Support;

/**
 * PLACEHOLDER product catalog for buyer-side category pages.
 *
 * 20 products per category, spread across its subcategories. Every entry below is
 * a stand-in — swap 'name', 'price', and 'emoji' (replace emoji with a real <img> in
 * the product-card partial once you have photos) for your gathered product data.
 * 'category' and 'subcategory' are slugs — they're what the category page filters on,
 * so keep them matching BuyerCategories::all() if you rename anything.
 *
 * Swap all() for a real query once a Product model/table exists, e.g.:
 * Product::where('category_slug', $categorySlug)->get()->toArray().
 */
class BuyerProducts
{
    public static function all(): array
    {
        return [

            // ---- Pet Supplies ----
            ['category' => 'pet-supplies', 'subcategory' => 'dog-food-and-treats', 'name' => "Dog Food & Treats — Sample Item 1", 'price' => '236', 'emoji' => '🐾', 'bg' => 'sand-400/25', 'rating' => 4.7, 'sold' => '103', 'slug' => 'pet-supplies-dog-food-and-treats-1'],
            ['category' => 'pet-supplies', 'subcategory' => 'dog-food-and-treats', 'name' => "Dog Food & Treats — Sample Item 2", 'price' => '273', 'emoji' => '🐾', 'bg' => 'maroon-700/10', 'rating' => 4.9, 'sold' => '156', 'slug' => 'pet-supplies-dog-food-and-treats-2'],
            ['category' => 'pet-supplies', 'subcategory' => 'dog-food-and-treats', 'name' => "Dog Food & Treats — Sample Item 3", 'price' => '310', 'emoji' => '🐾', 'bg' => 'gold-500/15', 'rating' => 4.6, 'sold' => '209', 'slug' => 'pet-supplies-dog-food-and-treats-3'],
            ['category' => 'pet-supplies', 'subcategory' => 'dog-food-and-treats', 'name' => "Dog Food & Treats — Sample Item 4", 'price' => '347', 'emoji' => '🐾', 'bg' => 'sand-400/25', 'rating' => 4.8, 'sold' => '262', 'slug' => 'pet-supplies-dog-food-and-treats-4'],
            ['category' => 'pet-supplies', 'subcategory' => 'cat-litter-and-accessories', 'name' => "Cat Litter & Accessories — Sample Item 1", 'price' => '384', 'emoji' => '🐾', 'bg' => 'maroon-700/10', 'rating' => 4.5, 'sold' => '315', 'slug' => 'pet-supplies-cat-litter-and-accessories-1'],
            ['category' => 'pet-supplies', 'subcategory' => 'cat-litter-and-accessories', 'name' => "Cat Litter & Accessories — Sample Item 2", 'price' => '421', 'emoji' => '🐾', 'bg' => 'gold-500/15', 'rating' => 4.7, 'sold' => '368', 'slug' => 'pet-supplies-cat-litter-and-accessories-2'],
            ['category' => 'pet-supplies', 'subcategory' => 'cat-litter-and-accessories', 'name' => "Cat Litter & Accessories — Sample Item 3", 'price' => '458', 'emoji' => '🐾', 'bg' => 'sand-400/25', 'rating' => 4.9, 'sold' => '421', 'slug' => 'pet-supplies-cat-litter-and-accessories-3'],
            ['category' => 'pet-supplies', 'subcategory' => 'cat-litter-and-accessories', 'name' => "Cat Litter & Accessories — Sample Item 4", 'price' => '495', 'emoji' => '🐾', 'bg' => 'maroon-700/10', 'rating' => 4.6, 'sold' => '474', 'slug' => 'pet-supplies-cat-litter-and-accessories-4'],
            ['category' => 'pet-supplies', 'subcategory' => 'aquariums-and-fish-supplies', 'name' => "Aquariums & Fish Supplies — Sample Item 1", 'price' => '532', 'emoji' => '🐾', 'bg' => 'gold-500/15', 'rating' => 4.8, 'sold' => '527', 'slug' => 'pet-supplies-aquariums-and-fish-supplies-1'],
            ['category' => 'pet-supplies', 'subcategory' => 'aquariums-and-fish-supplies', 'name' => "Aquariums & Fish Supplies — Sample Item 2", 'price' => '569', 'emoji' => '🐾', 'bg' => 'sand-400/25', 'rating' => 4.5, 'sold' => '580', 'slug' => 'pet-supplies-aquariums-and-fish-supplies-2'],
            ['category' => 'pet-supplies', 'subcategory' => 'aquariums-and-fish-supplies', 'name' => "Aquariums & Fish Supplies — Sample Item 3", 'price' => '606', 'emoji' => '🐾', 'bg' => 'maroon-700/10', 'rating' => 4.7, 'sold' => '633', 'slug' => 'pet-supplies-aquariums-and-fish-supplies-3'],
            ['category' => 'pet-supplies', 'subcategory' => 'bird-feeders-and-food', 'name' => "Bird Feeders & Food — Sample Item 1", 'price' => '643', 'emoji' => '🐾', 'bg' => 'gold-500/15', 'rating' => 4.9, 'sold' => '686', 'slug' => 'pet-supplies-bird-feeders-and-food-1'],
            ['category' => 'pet-supplies', 'subcategory' => 'bird-feeders-and-food', 'name' => "Bird Feeders & Food — Sample Item 2", 'price' => '680', 'emoji' => '🐾', 'bg' => 'sand-400/25', 'rating' => 4.6, 'sold' => '739', 'slug' => 'pet-supplies-bird-feeders-and-food-2'],
            ['category' => 'pet-supplies', 'subcategory' => 'bird-feeders-and-food', 'name' => "Bird Feeders & Food — Sample Item 3", 'price' => '717', 'emoji' => '🐾', 'bg' => 'maroon-700/10', 'rating' => 4.8, 'sold' => '792', 'slug' => 'pet-supplies-bird-feeders-and-food-3'],
            ['category' => 'pet-supplies', 'subcategory' => 'pet-grooming-products', 'name' => "Pet Grooming Products — Sample Item 1", 'price' => '754', 'emoji' => '🐾', 'bg' => 'gold-500/15', 'rating' => 4.5, 'sold' => '845', 'slug' => 'pet-supplies-pet-grooming-products-1'],
            ['category' => 'pet-supplies', 'subcategory' => 'pet-grooming-products', 'name' => "Pet Grooming Products — Sample Item 2", 'price' => '791', 'emoji' => '🐾', 'bg' => 'sand-400/25', 'rating' => 4.7, 'sold' => '898', 'slug' => 'pet-supplies-pet-grooming-products-2'],
            ['category' => 'pet-supplies', 'subcategory' => 'pet-grooming-products', 'name' => "Pet Grooming Products — Sample Item 3", 'price' => '828', 'emoji' => '🐾', 'bg' => 'maroon-700/10', 'rating' => 4.9, 'sold' => '51', 'slug' => 'pet-supplies-pet-grooming-products-3'],
            ['category' => 'pet-supplies', 'subcategory' => 'pet-health-and-wellness', 'name' => "Pet Health & Wellness — Sample Item 1", 'price' => '865', 'emoji' => '🐾', 'bg' => 'gold-500/15', 'rating' => 4.6, 'sold' => '104', 'slug' => 'pet-supplies-pet-health-and-wellness-1'],
            ['category' => 'pet-supplies', 'subcategory' => 'pet-health-and-wellness', 'name' => "Pet Health & Wellness — Sample Item 2", 'price' => '902', 'emoji' => '🐾', 'bg' => 'sand-400/25', 'rating' => 4.8, 'sold' => '157', 'slug' => 'pet-supplies-pet-health-and-wellness-2'],
            ['category' => 'pet-supplies', 'subcategory' => 'pet-health-and-wellness', 'name' => "Pet Health & Wellness — Sample Item 3", 'price' => '939', 'emoji' => '🐾', 'bg' => 'maroon-700/10', 'rating' => 4.5, 'sold' => '210', 'slug' => 'pet-supplies-pet-health-and-wellness-3'],

            // ---- Kids & Baby ----
            ['category' => 'kids-and-baby', 'subcategory' => 'baby-clothes-and-accessories', 'name' => "Baby Clothes & Accessories — Sample Item 1", 'price' => '236', 'emoji' => '🍼', 'bg' => 'gold-500/15', 'rating' => 4.7, 'sold' => '103', 'slug' => 'kids-and-baby-baby-clothes-and-accessories-1'],
            ['category' => 'kids-and-baby', 'subcategory' => 'baby-clothes-and-accessories', 'name' => "Baby Clothes & Accessories — Sample Item 2", 'price' => '273', 'emoji' => '🍼', 'bg' => 'sand-400/25', 'rating' => 4.9, 'sold' => '156', 'slug' => 'kids-and-baby-baby-clothes-and-accessories-2'],
            ['category' => 'kids-and-baby', 'subcategory' => 'baby-clothes-and-accessories', 'name' => "Baby Clothes & Accessories — Sample Item 3", 'price' => '310', 'emoji' => '🍼', 'bg' => 'maroon-700/10', 'rating' => 4.6, 'sold' => '209', 'slug' => 'kids-and-baby-baby-clothes-and-accessories-3'],
            ['category' => 'kids-and-baby', 'subcategory' => 'baby-clothes-and-accessories', 'name' => "Baby Clothes & Accessories — Sample Item 4", 'price' => '347', 'emoji' => '🍼', 'bg' => 'gold-500/15', 'rating' => 4.8, 'sold' => '262', 'slug' => 'kids-and-baby-baby-clothes-and-accessories-4'],
            ['category' => 'kids-and-baby', 'subcategory' => 'toys-and-games', 'name' => "Toys & Games — Sample Item 1", 'price' => '384', 'emoji' => '🍼', 'bg' => 'sand-400/25', 'rating' => 4.5, 'sold' => '315', 'slug' => 'kids-and-baby-toys-and-games-1'],
            ['category' => 'kids-and-baby', 'subcategory' => 'toys-and-games', 'name' => "Toys & Games — Sample Item 2", 'price' => '421', 'emoji' => '🍼', 'bg' => 'maroon-700/10', 'rating' => 4.7, 'sold' => '368', 'slug' => 'kids-and-baby-toys-and-games-2'],
            ['category' => 'kids-and-baby', 'subcategory' => 'toys-and-games', 'name' => "Toys & Games — Sample Item 3", 'price' => '458', 'emoji' => '🍼', 'bg' => 'gold-500/15', 'rating' => 4.9, 'sold' => '421', 'slug' => 'kids-and-baby-toys-and-games-3'],
            ['category' => 'kids-and-baby', 'subcategory' => 'toys-and-games', 'name' => "Toys & Games — Sample Item 4", 'price' => '495', 'emoji' => '🍼', 'bg' => 'sand-400/25', 'rating' => 4.6, 'sold' => '474', 'slug' => 'kids-and-baby-toys-and-games-4'],
            ['category' => 'kids-and-baby', 'subcategory' => 'educational-materials', 'name' => "Educational Materials — Sample Item 1", 'price' => '532', 'emoji' => '🍼', 'bg' => 'maroon-700/10', 'rating' => 4.8, 'sold' => '527', 'slug' => 'kids-and-baby-educational-materials-1'],
            ['category' => 'kids-and-baby', 'subcategory' => 'educational-materials', 'name' => "Educational Materials — Sample Item 2", 'price' => '569', 'emoji' => '🍼', 'bg' => 'gold-500/15', 'rating' => 4.5, 'sold' => '580', 'slug' => 'kids-and-baby-educational-materials-2'],
            ['category' => 'kids-and-baby', 'subcategory' => 'educational-materials', 'name' => "Educational Materials — Sample Item 3", 'price' => '606', 'emoji' => '🍼', 'bg' => 'sand-400/25', 'rating' => 4.7, 'sold' => '633', 'slug' => 'kids-and-baby-educational-materials-3'],
            ['category' => 'kids-and-baby', 'subcategory' => 'strollers-and-gear', 'name' => "Strollers & Gear — Sample Item 1", 'price' => '643', 'emoji' => '🍼', 'bg' => 'maroon-700/10', 'rating' => 4.9, 'sold' => '686', 'slug' => 'kids-and-baby-strollers-and-gear-1'],
            ['category' => 'kids-and-baby', 'subcategory' => 'strollers-and-gear', 'name' => "Strollers & Gear — Sample Item 2", 'price' => '680', 'emoji' => '🍼', 'bg' => 'gold-500/15', 'rating' => 4.6, 'sold' => '739', 'slug' => 'kids-and-baby-strollers-and-gear-2'],
            ['category' => 'kids-and-baby', 'subcategory' => 'strollers-and-gear', 'name' => "Strollers & Gear — Sample Item 3", 'price' => '717', 'emoji' => '🍼', 'bg' => 'sand-400/25', 'rating' => 4.8, 'sold' => '792', 'slug' => 'kids-and-baby-strollers-and-gear-3'],
            ['category' => 'kids-and-baby', 'subcategory' => 'nursery-furniture', 'name' => "Nursery Furniture — Sample Item 1", 'price' => '754', 'emoji' => '🍼', 'bg' => 'maroon-700/10', 'rating' => 4.5, 'sold' => '845', 'slug' => 'kids-and-baby-nursery-furniture-1'],
            ['category' => 'kids-and-baby', 'subcategory' => 'nursery-furniture', 'name' => "Nursery Furniture — Sample Item 2", 'price' => '791', 'emoji' => '🍼', 'bg' => 'gold-500/15', 'rating' => 4.7, 'sold' => '898', 'slug' => 'kids-and-baby-nursery-furniture-2'],
            ['category' => 'kids-and-baby', 'subcategory' => 'nursery-furniture', 'name' => "Nursery Furniture — Sample Item 3", 'price' => '828', 'emoji' => '🍼', 'bg' => 'sand-400/25', 'rating' => 4.9, 'sold' => '51', 'slug' => 'kids-and-baby-nursery-furniture-3'],
            ['category' => 'kids-and-baby', 'subcategory' => 'safety-and-health', 'name' => "Safety and Health — Sample Item 1", 'price' => '865', 'emoji' => '🍼', 'bg' => 'maroon-700/10', 'rating' => 4.6, 'sold' => '104', 'slug' => 'kids-and-baby-safety-and-health-1'],
            ['category' => 'kids-and-baby', 'subcategory' => 'safety-and-health', 'name' => "Safety and Health — Sample Item 2", 'price' => '902', 'emoji' => '🍼', 'bg' => 'gold-500/15', 'rating' => 4.8, 'sold' => '157', 'slug' => 'kids-and-baby-safety-and-health-2'],
            ['category' => 'kids-and-baby', 'subcategory' => 'safety-and-health', 'name' => "Safety and Health — Sample Item 3", 'price' => '939', 'emoji' => '🍼', 'bg' => 'sand-400/25', 'rating' => 4.5, 'sold' => '210', 'slug' => 'kids-and-baby-safety-and-health-3'],

            // ---- Electronics & Gadgets ----
            ['category' => 'electronics-and-gadgets', 'subcategory' => 'mobile-phones-and-accessories', 'name' => "Mobile Phones & Accessories — Sample Item 1", 'price' => '236', 'emoji' => '🔌', 'bg' => 'maroon-700/10', 'rating' => 4.7, 'sold' => '103', 'slug' => 'electronics-and-gadgets-mobile-phones-and-accessories-1'],
            ['category' => 'electronics-and-gadgets', 'subcategory' => 'mobile-phones-and-accessories', 'name' => "Mobile Phones & Accessories — Sample Item 2", 'price' => '273', 'emoji' => '🔌', 'bg' => 'gold-500/15', 'rating' => 4.9, 'sold' => '156', 'slug' => 'electronics-and-gadgets-mobile-phones-and-accessories-2'],
            ['category' => 'electronics-and-gadgets', 'subcategory' => 'mobile-phones-and-accessories', 'name' => "Mobile Phones & Accessories — Sample Item 3", 'price' => '310', 'emoji' => '🔌', 'bg' => 'sand-400/25', 'rating' => 4.6, 'sold' => '209', 'slug' => 'electronics-and-gadgets-mobile-phones-and-accessories-3'],
            ['category' => 'electronics-and-gadgets', 'subcategory' => 'mobile-phones-and-accessories', 'name' => "Mobile Phones & Accessories — Sample Item 4", 'price' => '347', 'emoji' => '🔌', 'bg' => 'maroon-700/10', 'rating' => 4.8, 'sold' => '262', 'slug' => 'electronics-and-gadgets-mobile-phones-and-accessories-4'],
            ['category' => 'electronics-and-gadgets', 'subcategory' => 'laptops-desktops-and-monitors', 'name' => "Laptops, Desktops & Monitors — Sample Item 1", 'price' => '384', 'emoji' => '🔌', 'bg' => 'gold-500/15', 'rating' => 4.5, 'sold' => '315', 'slug' => 'electronics-and-gadgets-laptops-desktops-and-monitors-1'],
            ['category' => 'electronics-and-gadgets', 'subcategory' => 'laptops-desktops-and-monitors', 'name' => "Laptops, Desktops & Monitors — Sample Item 2", 'price' => '421', 'emoji' => '🔌', 'bg' => 'sand-400/25', 'rating' => 4.7, 'sold' => '368', 'slug' => 'electronics-and-gadgets-laptops-desktops-and-monitors-2'],
            ['category' => 'electronics-and-gadgets', 'subcategory' => 'laptops-desktops-and-monitors', 'name' => "Laptops, Desktops & Monitors — Sample Item 3", 'price' => '458', 'emoji' => '🔌', 'bg' => 'maroon-700/10', 'rating' => 4.9, 'sold' => '421', 'slug' => 'electronics-and-gadgets-laptops-desktops-and-monitors-3'],
            ['category' => 'electronics-and-gadgets', 'subcategory' => 'laptops-desktops-and-monitors', 'name' => "Laptops, Desktops & Monitors — Sample Item 4", 'price' => '495', 'emoji' => '🔌', 'bg' => 'gold-500/15', 'rating' => 4.6, 'sold' => '474', 'slug' => 'electronics-and-gadgets-laptops-desktops-and-monitors-4'],
            ['category' => 'electronics-and-gadgets', 'subcategory' => 'audio-and-video-equipment', 'name' => "Audio & Video Equipment — Sample Item 1", 'price' => '532', 'emoji' => '🔌', 'bg' => 'sand-400/25', 'rating' => 4.8, 'sold' => '527', 'slug' => 'electronics-and-gadgets-audio-and-video-equipment-1'],
            ['category' => 'electronics-and-gadgets', 'subcategory' => 'audio-and-video-equipment', 'name' => "Audio & Video Equipment — Sample Item 2", 'price' => '569', 'emoji' => '🔌', 'bg' => 'maroon-700/10', 'rating' => 4.5, 'sold' => '580', 'slug' => 'electronics-and-gadgets-audio-and-video-equipment-2'],
            ['category' => 'electronics-and-gadgets', 'subcategory' => 'audio-and-video-equipment', 'name' => "Audio & Video Equipment — Sample Item 3", 'price' => '606', 'emoji' => '🔌', 'bg' => 'gold-500/15', 'rating' => 4.7, 'sold' => '633', 'slug' => 'electronics-and-gadgets-audio-and-video-equipment-3'],
            ['category' => 'electronics-and-gadgets', 'subcategory' => 'smart-home-devices', 'name' => "Smart Home Devices — Sample Item 1", 'price' => '643', 'emoji' => '🔌', 'bg' => 'sand-400/25', 'rating' => 4.9, 'sold' => '686', 'slug' => 'electronics-and-gadgets-smart-home-devices-1'],
            ['category' => 'electronics-and-gadgets', 'subcategory' => 'smart-home-devices', 'name' => "Smart Home Devices — Sample Item 2", 'price' => '680', 'emoji' => '🔌', 'bg' => 'maroon-700/10', 'rating' => 4.6, 'sold' => '739', 'slug' => 'electronics-and-gadgets-smart-home-devices-2'],
            ['category' => 'electronics-and-gadgets', 'subcategory' => 'smart-home-devices', 'name' => "Smart Home Devices — Sample Item 3", 'price' => '717', 'emoji' => '🔌', 'bg' => 'gold-500/15', 'rating' => 4.8, 'sold' => '792', 'slug' => 'electronics-and-gadgets-smart-home-devices-3'],
            ['category' => 'electronics-and-gadgets', 'subcategory' => 'cameras-and-photography', 'name' => "Cameras & Photography — Sample Item 1", 'price' => '754', 'emoji' => '🔌', 'bg' => 'sand-400/25', 'rating' => 4.5, 'sold' => '845', 'slug' => 'electronics-and-gadgets-cameras-and-photography-1'],
            ['category' => 'electronics-and-gadgets', 'subcategory' => 'cameras-and-photography', 'name' => "Cameras & Photography — Sample Item 2", 'price' => '791', 'emoji' => '🔌', 'bg' => 'maroon-700/10', 'rating' => 4.7, 'sold' => '898', 'slug' => 'electronics-and-gadgets-cameras-and-photography-2'],
            ['category' => 'electronics-and-gadgets', 'subcategory' => 'cameras-and-photography', 'name' => "Cameras & Photography — Sample Item 3", 'price' => '828', 'emoji' => '🔌', 'bg' => 'gold-500/15', 'rating' => 4.9, 'sold' => '51', 'slug' => 'electronics-and-gadgets-cameras-and-photography-3'],
            ['category' => 'electronics-and-gadgets', 'subcategory' => 'wearable-technology', 'name' => "Wearable Technology — Sample Item 1", 'price' => '865', 'emoji' => '🔌', 'bg' => 'sand-400/25', 'rating' => 4.6, 'sold' => '104', 'slug' => 'electronics-and-gadgets-wearable-technology-1'],
            ['category' => 'electronics-and-gadgets', 'subcategory' => 'wearable-technology', 'name' => "Wearable Technology — Sample Item 2", 'price' => '902', 'emoji' => '🔌', 'bg' => 'maroon-700/10', 'rating' => 4.8, 'sold' => '157', 'slug' => 'electronics-and-gadgets-wearable-technology-2'],
            ['category' => 'electronics-and-gadgets', 'subcategory' => 'wearable-technology', 'name' => "Wearable Technology — Sample Item 3", 'price' => '939', 'emoji' => '🔌', 'bg' => 'gold-500/15', 'rating' => 4.5, 'sold' => '210', 'slug' => 'electronics-and-gadgets-wearable-technology-3'],

            // ---- Home & Garden ----
            ['category' => 'home-and-garden', 'subcategory' => 'kitchen-appliances', 'name' => "Kitchen Appliances — Sample Item 1", 'price' => '236', 'emoji' => '🌿', 'bg' => 'sand-400/25', 'rating' => 4.7, 'sold' => '103', 'slug' => 'home-and-garden-kitchen-appliances-1'],
            ['category' => 'home-and-garden', 'subcategory' => 'kitchen-appliances', 'name' => "Kitchen Appliances — Sample Item 2", 'price' => '273', 'emoji' => '🌿', 'bg' => 'maroon-700/10', 'rating' => 4.9, 'sold' => '156', 'slug' => 'home-and-garden-kitchen-appliances-2'],
            ['category' => 'home-and-garden', 'subcategory' => 'kitchen-appliances', 'name' => "Kitchen Appliances — Sample Item 3", 'price' => '310', 'emoji' => '🌿', 'bg' => 'gold-500/15', 'rating' => 4.6, 'sold' => '209', 'slug' => 'home-and-garden-kitchen-appliances-3'],
            ['category' => 'home-and-garden', 'subcategory' => 'kitchen-appliances', 'name' => "Kitchen Appliances — Sample Item 4", 'price' => '347', 'emoji' => '🌿', 'bg' => 'sand-400/25', 'rating' => 4.8, 'sold' => '262', 'slug' => 'home-and-garden-kitchen-appliances-4'],
            ['category' => 'home-and-garden', 'subcategory' => 'furniture-and-decor', 'name' => "Furniture & Decor — Sample Item 1", 'price' => '384', 'emoji' => '🌿', 'bg' => 'maroon-700/10', 'rating' => 4.5, 'sold' => '315', 'slug' => 'home-and-garden-furniture-and-decor-1'],
            ['category' => 'home-and-garden', 'subcategory' => 'furniture-and-decor', 'name' => "Furniture & Decor — Sample Item 2", 'price' => '421', 'emoji' => '🌿', 'bg' => 'gold-500/15', 'rating' => 4.7, 'sold' => '368', 'slug' => 'home-and-garden-furniture-and-decor-2'],
            ['category' => 'home-and-garden', 'subcategory' => 'furniture-and-decor', 'name' => "Furniture & Decor — Sample Item 3", 'price' => '458', 'emoji' => '🌿', 'bg' => 'sand-400/25', 'rating' => 4.9, 'sold' => '421', 'slug' => 'home-and-garden-furniture-and-decor-3'],
            ['category' => 'home-and-garden', 'subcategory' => 'furniture-and-decor', 'name' => "Furniture & Decor — Sample Item 4", 'price' => '495', 'emoji' => '🌿', 'bg' => 'maroon-700/10', 'rating' => 4.6, 'sold' => '474', 'slug' => 'home-and-garden-furniture-and-decor-4'],
            ['category' => 'home-and-garden', 'subcategory' => 'gardening-tools', 'name' => "Gardening Tools — Sample Item 1", 'price' => '532', 'emoji' => '🌿', 'bg' => 'gold-500/15', 'rating' => 4.8, 'sold' => '527', 'slug' => 'home-and-garden-gardening-tools-1'],
            ['category' => 'home-and-garden', 'subcategory' => 'gardening-tools', 'name' => "Gardening Tools — Sample Item 2", 'price' => '569', 'emoji' => '🌿', 'bg' => 'sand-400/25', 'rating' => 4.5, 'sold' => '580', 'slug' => 'home-and-garden-gardening-tools-2'],
            ['category' => 'home-and-garden', 'subcategory' => 'gardening-tools', 'name' => "Gardening Tools — Sample Item 3", 'price' => '606', 'emoji' => '🌿', 'bg' => 'maroon-700/10', 'rating' => 4.7, 'sold' => '633', 'slug' => 'home-and-garden-gardening-tools-3'],
            ['category' => 'home-and-garden', 'subcategory' => 'outdoor-living', 'name' => "Outdoor Living — Sample Item 1", 'price' => '643', 'emoji' => '🌿', 'bg' => 'gold-500/15', 'rating' => 4.9, 'sold' => '686', 'slug' => 'home-and-garden-outdoor-living-1'],
            ['category' => 'home-and-garden', 'subcategory' => 'outdoor-living', 'name' => "Outdoor Living — Sample Item 2", 'price' => '680', 'emoji' => '🌿', 'bg' => 'sand-400/25', 'rating' => 4.6, 'sold' => '739', 'slug' => 'home-and-garden-outdoor-living-2'],
            ['category' => 'home-and-garden', 'subcategory' => 'outdoor-living', 'name' => "Outdoor Living — Sample Item 3", 'price' => '717', 'emoji' => '🌿', 'bg' => 'maroon-700/10', 'rating' => 4.8, 'sold' => '792', 'slug' => 'home-and-garden-outdoor-living-3'],
            ['category' => 'home-and-garden', 'subcategory' => 'home-improvement-tools', 'name' => "Home Improvement Tools — Sample Item 1", 'price' => '754', 'emoji' => '🌿', 'bg' => 'gold-500/15', 'rating' => 4.5, 'sold' => '845', 'slug' => 'home-and-garden-home-improvement-tools-1'],
            ['category' => 'home-and-garden', 'subcategory' => 'home-improvement-tools', 'name' => "Home Improvement Tools — Sample Item 2", 'price' => '791', 'emoji' => '🌿', 'bg' => 'sand-400/25', 'rating' => 4.7, 'sold' => '898', 'slug' => 'home-and-garden-home-improvement-tools-2'],
            ['category' => 'home-and-garden', 'subcategory' => 'home-improvement-tools', 'name' => "Home Improvement Tools — Sample Item 3", 'price' => '828', 'emoji' => '🌿', 'bg' => 'maroon-700/10', 'rating' => 4.9, 'sold' => '51', 'slug' => 'home-and-garden-home-improvement-tools-3'],
            ['category' => 'home-and-garden', 'subcategory' => 'bedding-and-bath', 'name' => "Bedding & Bath — Sample Item 1", 'price' => '865', 'emoji' => '🌿', 'bg' => 'gold-500/15', 'rating' => 4.6, 'sold' => '104', 'slug' => 'home-and-garden-bedding-and-bath-1'],
            ['category' => 'home-and-garden', 'subcategory' => 'bedding-and-bath', 'name' => "Bedding & Bath — Sample Item 2", 'price' => '902', 'emoji' => '🌿', 'bg' => 'sand-400/25', 'rating' => 4.8, 'sold' => '157', 'slug' => 'home-and-garden-bedding-and-bath-2'],
            ['category' => 'home-and-garden', 'subcategory' => 'bedding-and-bath', 'name' => "Bedding & Bath — Sample Item 3", 'price' => '939', 'emoji' => '🌿', 'bg' => 'maroon-700/10', 'rating' => 4.5, 'sold' => '210', 'slug' => 'home-and-garden-bedding-and-bath-3'],

            // ---- Women's Apparel ----
            ['category' => 'womens-apparel', 'subcategory' => 'dresses-and-skirts', 'name' => "Dresses & Skirts — Sample Item 1", 'price' => '236', 'emoji' => '👗', 'bg' => 'gold-500/15', 'rating' => 4.7, 'sold' => '103', 'slug' => 'womens-apparel-dresses-and-skirts-1'],
            ['category' => 'womens-apparel', 'subcategory' => 'dresses-and-skirts', 'name' => "Dresses & Skirts — Sample Item 2", 'price' => '273', 'emoji' => '👗', 'bg' => 'sand-400/25', 'rating' => 4.9, 'sold' => '156', 'slug' => 'womens-apparel-dresses-and-skirts-2'],
            ['category' => 'womens-apparel', 'subcategory' => 'dresses-and-skirts', 'name' => "Dresses & Skirts — Sample Item 3", 'price' => '310', 'emoji' => '👗', 'bg' => 'maroon-700/10', 'rating' => 4.6, 'sold' => '209', 'slug' => 'womens-apparel-dresses-and-skirts-3'],
            ['category' => 'womens-apparel', 'subcategory' => 'dresses-and-skirts', 'name' => "Dresses & Skirts — Sample Item 4", 'price' => '347', 'emoji' => '👗', 'bg' => 'gold-500/15', 'rating' => 4.8, 'sold' => '262', 'slug' => 'womens-apparel-dresses-and-skirts-4'],
            ['category' => 'womens-apparel', 'subcategory' => 'tops-and-blouses', 'name' => "Tops & Blouses — Sample Item 1", 'price' => '384', 'emoji' => '👗', 'bg' => 'sand-400/25', 'rating' => 4.5, 'sold' => '315', 'slug' => 'womens-apparel-tops-and-blouses-1'],
            ['category' => 'womens-apparel', 'subcategory' => 'tops-and-blouses', 'name' => "Tops & Blouses — Sample Item 2", 'price' => '421', 'emoji' => '👗', 'bg' => 'maroon-700/10', 'rating' => 4.7, 'sold' => '368', 'slug' => 'womens-apparel-tops-and-blouses-2'],
            ['category' => 'womens-apparel', 'subcategory' => 'tops-and-blouses', 'name' => "Tops & Blouses — Sample Item 3", 'price' => '458', 'emoji' => '👗', 'bg' => 'gold-500/15', 'rating' => 4.9, 'sold' => '421', 'slug' => 'womens-apparel-tops-and-blouses-3'],
            ['category' => 'womens-apparel', 'subcategory' => 'tops-and-blouses', 'name' => "Tops & Blouses — Sample Item 4", 'price' => '495', 'emoji' => '👗', 'bg' => 'sand-400/25', 'rating' => 4.6, 'sold' => '474', 'slug' => 'womens-apparel-tops-and-blouses-4'],
            ['category' => 'womens-apparel', 'subcategory' => 'activewear-and-yoga-pants', 'name' => "Activewear & Yoga Pants — Sample Item 1", 'price' => '532', 'emoji' => '👗', 'bg' => 'maroon-700/10', 'rating' => 4.8, 'sold' => '527', 'slug' => 'womens-apparel-activewear-and-yoga-pants-1'],
            ['category' => 'womens-apparel', 'subcategory' => 'activewear-and-yoga-pants', 'name' => "Activewear & Yoga Pants — Sample Item 2", 'price' => '569', 'emoji' => '👗', 'bg' => 'gold-500/15', 'rating' => 4.5, 'sold' => '580', 'slug' => 'womens-apparel-activewear-and-yoga-pants-2'],
            ['category' => 'womens-apparel', 'subcategory' => 'activewear-and-yoga-pants', 'name' => "Activewear & Yoga Pants — Sample Item 3", 'price' => '606', 'emoji' => '👗', 'bg' => 'sand-400/25', 'rating' => 4.7, 'sold' => '633', 'slug' => 'womens-apparel-activewear-and-yoga-pants-3'],
            ['category' => 'womens-apparel', 'subcategory' => 'lingerie-and-sleepwear', 'name' => "Lingerie & Sleepwear — Sample Item 1", 'price' => '643', 'emoji' => '👗', 'bg' => 'maroon-700/10', 'rating' => 4.9, 'sold' => '686', 'slug' => 'womens-apparel-lingerie-and-sleepwear-1'],
            ['category' => 'womens-apparel', 'subcategory' => 'lingerie-and-sleepwear', 'name' => "Lingerie & Sleepwear — Sample Item 2", 'price' => '680', 'emoji' => '👗', 'bg' => 'gold-500/15', 'rating' => 4.6, 'sold' => '739', 'slug' => 'womens-apparel-lingerie-and-sleepwear-2'],
            ['category' => 'womens-apparel', 'subcategory' => 'lingerie-and-sleepwear', 'name' => "Lingerie & Sleepwear — Sample Item 3", 'price' => '717', 'emoji' => '👗', 'bg' => 'sand-400/25', 'rating' => 4.8, 'sold' => '792', 'slug' => 'womens-apparel-lingerie-and-sleepwear-3'],
            ['category' => 'womens-apparel', 'subcategory' => 'jackets-and-coats', 'name' => "Jackets & Coats — Sample Item 1", 'price' => '754', 'emoji' => '👗', 'bg' => 'maroon-700/10', 'rating' => 4.5, 'sold' => '845', 'slug' => 'womens-apparel-jackets-and-coats-1'],
            ['category' => 'womens-apparel', 'subcategory' => 'jackets-and-coats', 'name' => "Jackets & Coats — Sample Item 2", 'price' => '791', 'emoji' => '👗', 'bg' => 'gold-500/15', 'rating' => 4.7, 'sold' => '898', 'slug' => 'womens-apparel-jackets-and-coats-2'],
            ['category' => 'womens-apparel', 'subcategory' => 'jackets-and-coats', 'name' => "Jackets & Coats — Sample Item 3", 'price' => '828', 'emoji' => '👗', 'bg' => 'sand-400/25', 'rating' => 4.9, 'sold' => '51', 'slug' => 'womens-apparel-jackets-and-coats-3'],
            ['category' => 'womens-apparel', 'subcategory' => 'shoes-and-accessories', 'name' => "Shoes & Accessories — Sample Item 1", 'price' => '865', 'emoji' => '👗', 'bg' => 'maroon-700/10', 'rating' => 4.6, 'sold' => '104', 'slug' => 'womens-apparel-shoes-and-accessories-1'],
            ['category' => 'womens-apparel', 'subcategory' => 'shoes-and-accessories', 'name' => "Shoes & Accessories — Sample Item 2", 'price' => '902', 'emoji' => '👗', 'bg' => 'gold-500/15', 'rating' => 4.8, 'sold' => '157', 'slug' => 'womens-apparel-shoes-and-accessories-2'],
            ['category' => 'womens-apparel', 'subcategory' => 'shoes-and-accessories', 'name' => "Shoes & Accessories — Sample Item 3", 'price' => '939', 'emoji' => '👗', 'bg' => 'sand-400/25', 'rating' => 4.5, 'sold' => '210', 'slug' => 'womens-apparel-shoes-and-accessories-3'],

            // ---- Sports & Outdoors ----
            ['category' => 'sports-and-outdoors', 'subcategory' => 'fitness-equipment', 'name' => "Fitness Equipment — Sample Item 1", 'price' => '236', 'emoji' => '🏸', 'bg' => 'maroon-700/10', 'rating' => 4.7, 'sold' => '103', 'slug' => 'sports-and-outdoors-fitness-equipment-1'],
            ['category' => 'sports-and-outdoors', 'subcategory' => 'fitness-equipment', 'name' => "Fitness Equipment — Sample Item 2", 'price' => '273', 'emoji' => '🏸', 'bg' => 'gold-500/15', 'rating' => 4.9, 'sold' => '156', 'slug' => 'sports-and-outdoors-fitness-equipment-2'],
            ['category' => 'sports-and-outdoors', 'subcategory' => 'fitness-equipment', 'name' => "Fitness Equipment — Sample Item 3", 'price' => '310', 'emoji' => '🏸', 'bg' => 'sand-400/25', 'rating' => 4.6, 'sold' => '209', 'slug' => 'sports-and-outdoors-fitness-equipment-3'],
            ['category' => 'sports-and-outdoors', 'subcategory' => 'fitness-equipment', 'name' => "Fitness Equipment — Sample Item 4", 'price' => '347', 'emoji' => '🏸', 'bg' => 'maroon-700/10', 'rating' => 4.8, 'sold' => '262', 'slug' => 'sports-and-outdoors-fitness-equipment-4'],
            ['category' => 'sports-and-outdoors', 'subcategory' => 'camping-and-hiking-gear', 'name' => "Camping & Hiking Gear — Sample Item 1", 'price' => '384', 'emoji' => '🏸', 'bg' => 'gold-500/15', 'rating' => 4.5, 'sold' => '315', 'slug' => 'sports-and-outdoors-camping-and-hiking-gear-1'],
            ['category' => 'sports-and-outdoors', 'subcategory' => 'camping-and-hiking-gear', 'name' => "Camping & Hiking Gear — Sample Item 2", 'price' => '421', 'emoji' => '🏸', 'bg' => 'sand-400/25', 'rating' => 4.7, 'sold' => '368', 'slug' => 'sports-and-outdoors-camping-and-hiking-gear-2'],
            ['category' => 'sports-and-outdoors', 'subcategory' => 'camping-and-hiking-gear', 'name' => "Camping & Hiking Gear — Sample Item 3", 'price' => '458', 'emoji' => '🏸', 'bg' => 'maroon-700/10', 'rating' => 4.9, 'sold' => '421', 'slug' => 'sports-and-outdoors-camping-and-hiking-gear-3'],
            ['category' => 'sports-and-outdoors', 'subcategory' => 'camping-and-hiking-gear', 'name' => "Camping & Hiking Gear — Sample Item 4", 'price' => '495', 'emoji' => '🏸', 'bg' => 'gold-500/15', 'rating' => 4.6, 'sold' => '474', 'slug' => 'sports-and-outdoors-camping-and-hiking-gear-4'],
            ['category' => 'sports-and-outdoors', 'subcategory' => 'sports-apparel', 'name' => "Sports Apparel — Sample Item 1", 'price' => '532', 'emoji' => '🏸', 'bg' => 'sand-400/25', 'rating' => 4.8, 'sold' => '527', 'slug' => 'sports-and-outdoors-sports-apparel-1'],
            ['category' => 'sports-and-outdoors', 'subcategory' => 'sports-apparel', 'name' => "Sports Apparel — Sample Item 2", 'price' => '569', 'emoji' => '🏸', 'bg' => 'maroon-700/10', 'rating' => 4.5, 'sold' => '580', 'slug' => 'sports-and-outdoors-sports-apparel-2'],
            ['category' => 'sports-and-outdoors', 'subcategory' => 'sports-apparel', 'name' => "Sports Apparel — Sample Item 3", 'price' => '606', 'emoji' => '🏸', 'bg' => 'gold-500/15', 'rating' => 4.7, 'sold' => '633', 'slug' => 'sports-and-outdoors-sports-apparel-3'],
            ['category' => 'sports-and-outdoors', 'subcategory' => 'cycling-and-bikes', 'name' => "Cycling & Bikes — Sample Item 1", 'price' => '643', 'emoji' => '🏸', 'bg' => 'sand-400/25', 'rating' => 4.9, 'sold' => '686', 'slug' => 'sports-and-outdoors-cycling-and-bikes-1'],
            ['category' => 'sports-and-outdoors', 'subcategory' => 'cycling-and-bikes', 'name' => "Cycling & Bikes — Sample Item 2", 'price' => '680', 'emoji' => '🏸', 'bg' => 'maroon-700/10', 'rating' => 4.6, 'sold' => '739', 'slug' => 'sports-and-outdoors-cycling-and-bikes-2'],
            ['category' => 'sports-and-outdoors', 'subcategory' => 'cycling-and-bikes', 'name' => "Cycling & Bikes — Sample Item 3", 'price' => '717', 'emoji' => '🏸', 'bg' => 'gold-500/15', 'rating' => 4.8, 'sold' => '792', 'slug' => 'sports-and-outdoors-cycling-and-bikes-3'],
            ['category' => 'sports-and-outdoors', 'subcategory' => 'water-sports', 'name' => "Water Sports — Sample Item 1", 'price' => '754', 'emoji' => '🏸', 'bg' => 'sand-400/25', 'rating' => 4.5, 'sold' => '845', 'slug' => 'sports-and-outdoors-water-sports-1'],
            ['category' => 'sports-and-outdoors', 'subcategory' => 'water-sports', 'name' => "Water Sports — Sample Item 2", 'price' => '791', 'emoji' => '🏸', 'bg' => 'maroon-700/10', 'rating' => 4.7, 'sold' => '898', 'slug' => 'sports-and-outdoors-water-sports-2'],
            ['category' => 'sports-and-outdoors', 'subcategory' => 'water-sports', 'name' => "Water Sports — Sample Item 3", 'price' => '828', 'emoji' => '🏸', 'bg' => 'gold-500/15', 'rating' => 4.9, 'sold' => '51', 'slug' => 'sports-and-outdoors-water-sports-3'],
            ['category' => 'sports-and-outdoors', 'subcategory' => 'team-sports-equipment', 'name' => "Team Sports Equipment — Sample Item 1", 'price' => '865', 'emoji' => '🏸', 'bg' => 'sand-400/25', 'rating' => 4.6, 'sold' => '104', 'slug' => 'sports-and-outdoors-team-sports-equipment-1'],
            ['category' => 'sports-and-outdoors', 'subcategory' => 'team-sports-equipment', 'name' => "Team Sports Equipment — Sample Item 2", 'price' => '902', 'emoji' => '🏸', 'bg' => 'maroon-700/10', 'rating' => 4.8, 'sold' => '157', 'slug' => 'sports-and-outdoors-team-sports-equipment-2'],
            ['category' => 'sports-and-outdoors', 'subcategory' => 'team-sports-equipment', 'name' => "Team Sports Equipment — Sample Item 3", 'price' => '939', 'emoji' => '🏸', 'bg' => 'gold-500/15', 'rating' => 4.5, 'sold' => '210', 'slug' => 'sports-and-outdoors-team-sports-equipment-3'],

            // ---- Men's Apparel ----
            ['category' => 'mens-apparel', 'subcategory' => 'suits-and-blazers', 'name' => "Suits & Blazers — Sample Item 1", 'price' => '236', 'emoji' => '👔', 'bg' => 'sand-400/25', 'rating' => 4.7, 'sold' => '103', 'slug' => 'mens-apparel-suits-and-blazers-1'],
            ['category' => 'mens-apparel', 'subcategory' => 'suits-and-blazers', 'name' => "Suits & Blazers — Sample Item 2", 'price' => '273', 'emoji' => '👔', 'bg' => 'maroon-700/10', 'rating' => 4.9, 'sold' => '156', 'slug' => 'mens-apparel-suits-and-blazers-2'],
            ['category' => 'mens-apparel', 'subcategory' => 'suits-and-blazers', 'name' => "Suits & Blazers — Sample Item 3", 'price' => '310', 'emoji' => '👔', 'bg' => 'gold-500/15', 'rating' => 4.6, 'sold' => '209', 'slug' => 'mens-apparel-suits-and-blazers-3'],
            ['category' => 'mens-apparel', 'subcategory' => 'suits-and-blazers', 'name' => "Suits & Blazers — Sample Item 4", 'price' => '347', 'emoji' => '👔', 'bg' => 'sand-400/25', 'rating' => 4.8, 'sold' => '262', 'slug' => 'mens-apparel-suits-and-blazers-4'],
            ['category' => 'mens-apparel', 'subcategory' => 'casual-shirts-and-pants', 'name' => "Casual Shirts & Pants — Sample Item 1", 'price' => '384', 'emoji' => '👔', 'bg' => 'maroon-700/10', 'rating' => 4.5, 'sold' => '315', 'slug' => 'mens-apparel-casual-shirts-and-pants-1'],
            ['category' => 'mens-apparel', 'subcategory' => 'casual-shirts-and-pants', 'name' => "Casual Shirts & Pants — Sample Item 2", 'price' => '421', 'emoji' => '👔', 'bg' => 'gold-500/15', 'rating' => 4.7, 'sold' => '368', 'slug' => 'mens-apparel-casual-shirts-and-pants-2'],
            ['category' => 'mens-apparel', 'subcategory' => 'casual-shirts-and-pants', 'name' => "Casual Shirts & Pants — Sample Item 3", 'price' => '458', 'emoji' => '👔', 'bg' => 'sand-400/25', 'rating' => 4.9, 'sold' => '421', 'slug' => 'mens-apparel-casual-shirts-and-pants-3'],
            ['category' => 'mens-apparel', 'subcategory' => 'casual-shirts-and-pants', 'name' => "Casual Shirts & Pants — Sample Item 4", 'price' => '495', 'emoji' => '👔', 'bg' => 'maroon-700/10', 'rating' => 4.6, 'sold' => '474', 'slug' => 'mens-apparel-casual-shirts-and-pants-4'],
            ['category' => 'mens-apparel', 'subcategory' => 'outerwear-and-jackets', 'name' => "Outerwear & Jackets — Sample Item 1", 'price' => '532', 'emoji' => '👔', 'bg' => 'gold-500/15', 'rating' => 4.8, 'sold' => '527', 'slug' => 'mens-apparel-outerwear-and-jackets-1'],
            ['category' => 'mens-apparel', 'subcategory' => 'outerwear-and-jackets', 'name' => "Outerwear & Jackets — Sample Item 2", 'price' => '569', 'emoji' => '👔', 'bg' => 'sand-400/25', 'rating' => 4.5, 'sold' => '580', 'slug' => 'mens-apparel-outerwear-and-jackets-2'],
            ['category' => 'mens-apparel', 'subcategory' => 'outerwear-and-jackets', 'name' => "Outerwear & Jackets — Sample Item 3", 'price' => '606', 'emoji' => '👔', 'bg' => 'maroon-700/10', 'rating' => 4.7, 'sold' => '633', 'slug' => 'mens-apparel-outerwear-and-jackets-3'],
            ['category' => 'mens-apparel', 'subcategory' => 'activewear-and-fitness-gear', 'name' => "Activewear & Fitness Gear — Sample Item 1", 'price' => '643', 'emoji' => '👔', 'bg' => 'gold-500/15', 'rating' => 4.9, 'sold' => '686', 'slug' => 'mens-apparel-activewear-and-fitness-gear-1'],
            ['category' => 'mens-apparel', 'subcategory' => 'activewear-and-fitness-gear', 'name' => "Activewear & Fitness Gear — Sample Item 2", 'price' => '680', 'emoji' => '👔', 'bg' => 'sand-400/25', 'rating' => 4.6, 'sold' => '739', 'slug' => 'mens-apparel-activewear-and-fitness-gear-2'],
            ['category' => 'mens-apparel', 'subcategory' => 'activewear-and-fitness-gear', 'name' => "Activewear & Fitness Gear — Sample Item 3", 'price' => '717', 'emoji' => '👔', 'bg' => 'maroon-700/10', 'rating' => 4.8, 'sold' => '792', 'slug' => 'mens-apparel-activewear-and-fitness-gear-3'],
            ['category' => 'mens-apparel', 'subcategory' => 'shoes-and-accessories', 'name' => "Shoes & Accessories — Sample Item 1", 'price' => '754', 'emoji' => '👔', 'bg' => 'gold-500/15', 'rating' => 4.5, 'sold' => '845', 'slug' => 'mens-apparel-shoes-and-accessories-1'],
            ['category' => 'mens-apparel', 'subcategory' => 'shoes-and-accessories', 'name' => "Shoes & Accessories — Sample Item 2", 'price' => '791', 'emoji' => '👔', 'bg' => 'sand-400/25', 'rating' => 4.7, 'sold' => '898', 'slug' => 'mens-apparel-shoes-and-accessories-2'],
            ['category' => 'mens-apparel', 'subcategory' => 'shoes-and-accessories', 'name' => "Shoes & Accessories — Sample Item 3", 'price' => '828', 'emoji' => '👔', 'bg' => 'maroon-700/10', 'rating' => 4.9, 'sold' => '51', 'slug' => 'mens-apparel-shoes-and-accessories-3'],
            ['category' => 'mens-apparel', 'subcategory' => 'grooming-products', 'name' => "Grooming Products — Sample Item 1", 'price' => '865', 'emoji' => '👔', 'bg' => 'gold-500/15', 'rating' => 4.6, 'sold' => '104', 'slug' => 'mens-apparel-grooming-products-1'],
            ['category' => 'mens-apparel', 'subcategory' => 'grooming-products', 'name' => "Grooming Products — Sample Item 2", 'price' => '902', 'emoji' => '👔', 'bg' => 'sand-400/25', 'rating' => 4.8, 'sold' => '157', 'slug' => 'mens-apparel-grooming-products-2'],
            ['category' => 'mens-apparel', 'subcategory' => 'grooming-products', 'name' => "Grooming Products — Sample Item 3", 'price' => '939', 'emoji' => '👔', 'bg' => 'maroon-700/10', 'rating' => 4.5, 'sold' => '210', 'slug' => 'mens-apparel-grooming-products-3'],

            // ---- Health & Beauty ----
            ['category' => 'health-and-beauty', 'subcategory' => 'skincare-products', 'name' => "Skincare Products — Sample Item 1", 'price' => '236', 'emoji' => '💄', 'bg' => 'gold-500/15', 'rating' => 4.7, 'sold' => '103', 'slug' => 'health-and-beauty-skincare-products-1'],
            ['category' => 'health-and-beauty', 'subcategory' => 'skincare-products', 'name' => "Skincare Products — Sample Item 2", 'price' => '273', 'emoji' => '💄', 'bg' => 'sand-400/25', 'rating' => 4.9, 'sold' => '156', 'slug' => 'health-and-beauty-skincare-products-2'],
            ['category' => 'health-and-beauty', 'subcategory' => 'skincare-products', 'name' => "Skincare Products — Sample Item 3", 'price' => '310', 'emoji' => '💄', 'bg' => 'maroon-700/10', 'rating' => 4.6, 'sold' => '209', 'slug' => 'health-and-beauty-skincare-products-3'],
            ['category' => 'health-and-beauty', 'subcategory' => 'skincare-products', 'name' => "Skincare Products — Sample Item 4", 'price' => '347', 'emoji' => '💄', 'bg' => 'gold-500/15', 'rating' => 4.8, 'sold' => '262', 'slug' => 'health-and-beauty-skincare-products-4'],
            ['category' => 'health-and-beauty', 'subcategory' => 'haircare-solutions', 'name' => "Haircare Solutions — Sample Item 1", 'price' => '384', 'emoji' => '💄', 'bg' => 'sand-400/25', 'rating' => 4.5, 'sold' => '315', 'slug' => 'health-and-beauty-haircare-solutions-1'],
            ['category' => 'health-and-beauty', 'subcategory' => 'haircare-solutions', 'name' => "Haircare Solutions — Sample Item 2", 'price' => '421', 'emoji' => '💄', 'bg' => 'maroon-700/10', 'rating' => 4.7, 'sold' => '368', 'slug' => 'health-and-beauty-haircare-solutions-2'],
            ['category' => 'health-and-beauty', 'subcategory' => 'haircare-solutions', 'name' => "Haircare Solutions — Sample Item 3", 'price' => '458', 'emoji' => '💄', 'bg' => 'gold-500/15', 'rating' => 4.9, 'sold' => '421', 'slug' => 'health-and-beauty-haircare-solutions-3'],
            ['category' => 'health-and-beauty', 'subcategory' => 'haircare-solutions', 'name' => "Haircare Solutions — Sample Item 4", 'price' => '495', 'emoji' => '💄', 'bg' => 'sand-400/25', 'rating' => 4.6, 'sold' => '474', 'slug' => 'health-and-beauty-haircare-solutions-4'],
            ['category' => 'health-and-beauty', 'subcategory' => 'makeup-and-cosmetics', 'name' => "Makeup & Cosmetics — Sample Item 1", 'price' => '532', 'emoji' => '💄', 'bg' => 'maroon-700/10', 'rating' => 4.8, 'sold' => '527', 'slug' => 'health-and-beauty-makeup-and-cosmetics-1'],
            ['category' => 'health-and-beauty', 'subcategory' => 'makeup-and-cosmetics', 'name' => "Makeup & Cosmetics — Sample Item 2", 'price' => '569', 'emoji' => '💄', 'bg' => 'gold-500/15', 'rating' => 4.5, 'sold' => '580', 'slug' => 'health-and-beauty-makeup-and-cosmetics-2'],
            ['category' => 'health-and-beauty', 'subcategory' => 'makeup-and-cosmetics', 'name' => "Makeup & Cosmetics — Sample Item 3", 'price' => '606', 'emoji' => '💄', 'bg' => 'sand-400/25', 'rating' => 4.7, 'sold' => '633', 'slug' => 'health-and-beauty-makeup-and-cosmetics-3'],
            ['category' => 'health-and-beauty', 'subcategory' => 'personal-care-appliances', 'name' => "Personal Care Appliances — Sample Item 1", 'price' => '643', 'emoji' => '💄', 'bg' => 'maroon-700/10', 'rating' => 4.9, 'sold' => '686', 'slug' => 'health-and-beauty-personal-care-appliances-1'],
            ['category' => 'health-and-beauty', 'subcategory' => 'personal-care-appliances', 'name' => "Personal Care Appliances — Sample Item 2", 'price' => '680', 'emoji' => '💄', 'bg' => 'gold-500/15', 'rating' => 4.6, 'sold' => '739', 'slug' => 'health-and-beauty-personal-care-appliances-2'],
            ['category' => 'health-and-beauty', 'subcategory' => 'personal-care-appliances', 'name' => "Personal Care Appliances — Sample Item 3", 'price' => '717', 'emoji' => '💄', 'bg' => 'sand-400/25', 'rating' => 4.8, 'sold' => '792', 'slug' => 'health-and-beauty-personal-care-appliances-3'],
            ['category' => 'health-and-beauty', 'subcategory' => 'mens-grooming', 'name' => "Men's Grooming — Sample Item 1", 'price' => '754', 'emoji' => '💄', 'bg' => 'maroon-700/10', 'rating' => 4.5, 'sold' => '845', 'slug' => 'health-and-beauty-mens-grooming-1'],
            ['category' => 'health-and-beauty', 'subcategory' => 'mens-grooming', 'name' => "Men's Grooming — Sample Item 2", 'price' => '791', 'emoji' => '💄', 'bg' => 'gold-500/15', 'rating' => 4.7, 'sold' => '898', 'slug' => 'health-and-beauty-mens-grooming-2'],
            ['category' => 'health-and-beauty', 'subcategory' => 'mens-grooming', 'name' => "Men's Grooming — Sample Item 3", 'price' => '828', 'emoji' => '💄', 'bg' => 'sand-400/25', 'rating' => 4.9, 'sold' => '51', 'slug' => 'health-and-beauty-mens-grooming-3'],
            ['category' => 'health-and-beauty', 'subcategory' => 'health-supplements', 'name' => "Health Supplements — Sample Item 1", 'price' => '865', 'emoji' => '💄', 'bg' => 'maroon-700/10', 'rating' => 4.6, 'sold' => '104', 'slug' => 'health-and-beauty-health-supplements-1'],
            ['category' => 'health-and-beauty', 'subcategory' => 'health-supplements', 'name' => "Health Supplements — Sample Item 2", 'price' => '902', 'emoji' => '💄', 'bg' => 'gold-500/15', 'rating' => 4.8, 'sold' => '157', 'slug' => 'health-and-beauty-health-supplements-2'],
            ['category' => 'health-and-beauty', 'subcategory' => 'health-supplements', 'name' => "Health Supplements — Sample Item 3", 'price' => '939', 'emoji' => '💄', 'bg' => 'sand-400/25', 'rating' => 4.5, 'sold' => '210', 'slug' => 'health-and-beauty-health-supplements-3'],

            // ---- Books & Media ----
            ['category' => 'books-and-media', 'subcategory' => 'fiction-and-non-fiction-books', 'name' => "Fiction & Non-Fiction Books — Sample Item 1", 'price' => '236', 'emoji' => '📚', 'bg' => 'maroon-700/10', 'rating' => 4.7, 'sold' => '103', 'slug' => 'books-and-media-fiction-and-non-fiction-books-1'],
            ['category' => 'books-and-media', 'subcategory' => 'fiction-and-non-fiction-books', 'name' => "Fiction & Non-Fiction Books — Sample Item 2", 'price' => '273', 'emoji' => '📚', 'bg' => 'gold-500/15', 'rating' => 4.9, 'sold' => '156', 'slug' => 'books-and-media-fiction-and-non-fiction-books-2'],
            ['category' => 'books-and-media', 'subcategory' => 'fiction-and-non-fiction-books', 'name' => "Fiction & Non-Fiction Books — Sample Item 3", 'price' => '310', 'emoji' => '📚', 'bg' => 'sand-400/25', 'rating' => 4.6, 'sold' => '209', 'slug' => 'books-and-media-fiction-and-non-fiction-books-3'],
            ['category' => 'books-and-media', 'subcategory' => 'fiction-and-non-fiction-books', 'name' => "Fiction & Non-Fiction Books — Sample Item 4", 'price' => '347', 'emoji' => '📚', 'bg' => 'maroon-700/10', 'rating' => 4.8, 'sold' => '262', 'slug' => 'books-and-media-fiction-and-non-fiction-books-4'],
            ['category' => 'books-and-media', 'subcategory' => 'magazines-and-periodicals', 'name' => "Magazines & Periodicals — Sample Item 1", 'price' => '384', 'emoji' => '📚', 'bg' => 'gold-500/15', 'rating' => 4.5, 'sold' => '315', 'slug' => 'books-and-media-magazines-and-periodicals-1'],
            ['category' => 'books-and-media', 'subcategory' => 'magazines-and-periodicals', 'name' => "Magazines & Periodicals — Sample Item 2", 'price' => '421', 'emoji' => '📚', 'bg' => 'sand-400/25', 'rating' => 4.7, 'sold' => '368', 'slug' => 'books-and-media-magazines-and-periodicals-2'],
            ['category' => 'books-and-media', 'subcategory' => 'magazines-and-periodicals', 'name' => "Magazines & Periodicals — Sample Item 3", 'price' => '458', 'emoji' => '📚', 'bg' => 'maroon-700/10', 'rating' => 4.9, 'sold' => '421', 'slug' => 'books-and-media-magazines-and-periodicals-3'],
            ['category' => 'books-and-media', 'subcategory' => 'magazines-and-periodicals', 'name' => "Magazines & Periodicals — Sample Item 4", 'price' => '495', 'emoji' => '📚', 'bg' => 'gold-500/15', 'rating' => 4.6, 'sold' => '474', 'slug' => 'books-and-media-magazines-and-periodicals-4'],
            ['category' => 'books-and-media', 'subcategory' => 'music-cds-and-vinyl-records', 'name' => "Music CDs & Vinyl Records — Sample Item 1", 'price' => '532', 'emoji' => '📚', 'bg' => 'sand-400/25', 'rating' => 4.8, 'sold' => '527', 'slug' => 'books-and-media-music-cds-and-vinyl-records-1'],
            ['category' => 'books-and-media', 'subcategory' => 'music-cds-and-vinyl-records', 'name' => "Music CDs & Vinyl Records — Sample Item 2", 'price' => '569', 'emoji' => '📚', 'bg' => 'maroon-700/10', 'rating' => 4.5, 'sold' => '580', 'slug' => 'books-and-media-music-cds-and-vinyl-records-2'],
            ['category' => 'books-and-media', 'subcategory' => 'music-cds-and-vinyl-records', 'name' => "Music CDs & Vinyl Records — Sample Item 3", 'price' => '606', 'emoji' => '📚', 'bg' => 'gold-500/15', 'rating' => 4.7, 'sold' => '633', 'slug' => 'books-and-media-music-cds-and-vinyl-records-3'],
            ['category' => 'books-and-media', 'subcategory' => 'movie-dvds-and-blu-ray', 'name' => "Movie DVDs & Blu-ray — Sample Item 1", 'price' => '643', 'emoji' => '📚', 'bg' => 'sand-400/25', 'rating' => 4.9, 'sold' => '686', 'slug' => 'books-and-media-movie-dvds-and-blu-ray-1'],
            ['category' => 'books-and-media', 'subcategory' => 'movie-dvds-and-blu-ray', 'name' => "Movie DVDs & Blu-ray — Sample Item 2", 'price' => '680', 'emoji' => '📚', 'bg' => 'maroon-700/10', 'rating' => 4.6, 'sold' => '739', 'slug' => 'books-and-media-movie-dvds-and-blu-ray-2'],
            ['category' => 'books-and-media', 'subcategory' => 'movie-dvds-and-blu-ray', 'name' => "Movie DVDs & Blu-ray — Sample Item 3", 'price' => '717', 'emoji' => '📚', 'bg' => 'gold-500/15', 'rating' => 4.8, 'sold' => '792', 'slug' => 'books-and-media-movie-dvds-and-blu-ray-3'],
            ['category' => 'books-and-media', 'subcategory' => 'video-games-and-consoles', 'name' => "Video Games & Consoles — Sample Item 1", 'price' => '754', 'emoji' => '📚', 'bg' => 'sand-400/25', 'rating' => 4.5, 'sold' => '845', 'slug' => 'books-and-media-video-games-and-consoles-1'],
            ['category' => 'books-and-media', 'subcategory' => 'video-games-and-consoles', 'name' => "Video Games & Consoles — Sample Item 2", 'price' => '791', 'emoji' => '📚', 'bg' => 'maroon-700/10', 'rating' => 4.7, 'sold' => '898', 'slug' => 'books-and-media-video-games-and-consoles-2'],
            ['category' => 'books-and-media', 'subcategory' => 'video-games-and-consoles', 'name' => "Video Games & Consoles — Sample Item 3", 'price' => '828', 'emoji' => '📚', 'bg' => 'gold-500/15', 'rating' => 4.9, 'sold' => '51', 'slug' => 'books-and-media-video-games-and-consoles-3'],
            ['category' => 'books-and-media', 'subcategory' => 'educational-dvds', 'name' => "Educational DVDs — Sample Item 1", 'price' => '865', 'emoji' => '📚', 'bg' => 'sand-400/25', 'rating' => 4.6, 'sold' => '104', 'slug' => 'books-and-media-educational-dvds-1'],
            ['category' => 'books-and-media', 'subcategory' => 'educational-dvds', 'name' => "Educational DVDs — Sample Item 2", 'price' => '902', 'emoji' => '📚', 'bg' => 'maroon-700/10', 'rating' => 4.8, 'sold' => '157', 'slug' => 'books-and-media-educational-dvds-2'],
            ['category' => 'books-and-media', 'subcategory' => 'educational-dvds', 'name' => "Educational DVDs — Sample Item 3", 'price' => '939', 'emoji' => '📚', 'bg' => 'gold-500/15', 'rating' => 4.5, 'sold' => '210', 'slug' => 'books-and-media-educational-dvds-3'],

            // ---- Food & Gourmet ----
            ['category' => 'food-and-gourmet', 'subcategory' => 'baking-supplies-and-ingredients', 'name' => "Baking Supplies & Ingredients — Sample Item 1", 'price' => '236', 'emoji' => '🍯', 'bg' => 'sand-400/25', 'rating' => 4.7, 'sold' => '103', 'slug' => 'food-and-gourmet-baking-supplies-and-ingredients-1'],
            ['category' => 'food-and-gourmet', 'subcategory' => 'baking-supplies-and-ingredients', 'name' => "Baking Supplies & Ingredients — Sample Item 2", 'price' => '273', 'emoji' => '🍯', 'bg' => 'maroon-700/10', 'rating' => 4.9, 'sold' => '156', 'slug' => 'food-and-gourmet-baking-supplies-and-ingredients-2'],
            ['category' => 'food-and-gourmet', 'subcategory' => 'baking-supplies-and-ingredients', 'name' => "Baking Supplies & Ingredients — Sample Item 3", 'price' => '310', 'emoji' => '🍯', 'bg' => 'gold-500/15', 'rating' => 4.6, 'sold' => '209', 'slug' => 'food-and-gourmet-baking-supplies-and-ingredients-3'],
            ['category' => 'food-and-gourmet', 'subcategory' => 'baking-supplies-and-ingredients', 'name' => "Baking Supplies & Ingredients — Sample Item 4", 'price' => '347', 'emoji' => '🍯', 'bg' => 'sand-400/25', 'rating' => 4.8, 'sold' => '262', 'slug' => 'food-and-gourmet-baking-supplies-and-ingredients-4'],
            ['category' => 'food-and-gourmet', 'subcategory' => 'coffee-tea-and-beverages', 'name' => "Coffee, Tea & Beverages — Sample Item 1", 'price' => '384', 'emoji' => '🍯', 'bg' => 'maroon-700/10', 'rating' => 4.5, 'sold' => '315', 'slug' => 'food-and-gourmet-coffee-tea-and-beverages-1'],
            ['category' => 'food-and-gourmet', 'subcategory' => 'coffee-tea-and-beverages', 'name' => "Coffee, Tea & Beverages — Sample Item 2", 'price' => '421', 'emoji' => '🍯', 'bg' => 'gold-500/15', 'rating' => 4.7, 'sold' => '368', 'slug' => 'food-and-gourmet-coffee-tea-and-beverages-2'],
            ['category' => 'food-and-gourmet', 'subcategory' => 'coffee-tea-and-beverages', 'name' => "Coffee, Tea & Beverages — Sample Item 3", 'price' => '458', 'emoji' => '🍯', 'bg' => 'sand-400/25', 'rating' => 4.9, 'sold' => '421', 'slug' => 'food-and-gourmet-coffee-tea-and-beverages-3'],
            ['category' => 'food-and-gourmet', 'subcategory' => 'coffee-tea-and-beverages', 'name' => "Coffee, Tea & Beverages — Sample Item 4", 'price' => '495', 'emoji' => '🍯', 'bg' => 'maroon-700/10', 'rating' => 4.6, 'sold' => '474', 'slug' => 'food-and-gourmet-coffee-tea-and-beverages-4'],
            ['category' => 'food-and-gourmet', 'subcategory' => 'snacks-and-candy', 'name' => "Snacks & Candy — Sample Item 1", 'price' => '532', 'emoji' => '🍯', 'bg' => 'gold-500/15', 'rating' => 4.8, 'sold' => '527', 'slug' => 'food-and-gourmet-snacks-and-candy-1'],
            ['category' => 'food-and-gourmet', 'subcategory' => 'snacks-and-candy', 'name' => "Snacks & Candy — Sample Item 2", 'price' => '569', 'emoji' => '🍯', 'bg' => 'sand-400/25', 'rating' => 4.5, 'sold' => '580', 'slug' => 'food-and-gourmet-snacks-and-candy-2'],
            ['category' => 'food-and-gourmet', 'subcategory' => 'snacks-and-candy', 'name' => "Snacks & Candy — Sample Item 3", 'price' => '606', 'emoji' => '🍯', 'bg' => 'maroon-700/10', 'rating' => 4.7, 'sold' => '633', 'slug' => 'food-and-gourmet-snacks-and-candy-3'],
            ['category' => 'food-and-gourmet', 'subcategory' => 'specialty-foods-and-international-cuisine', 'name' => "Specialty Foods & International Cuisine — Sample Item 1", 'price' => '643', 'emoji' => '🍯', 'bg' => 'gold-500/15', 'rating' => 4.9, 'sold' => '686', 'slug' => 'food-and-gourmet-specialty-foods-and-international-cuisine-1'],
            ['category' => 'food-and-gourmet', 'subcategory' => 'specialty-foods-and-international-cuisine', 'name' => "Specialty Foods & International Cuisine — Sample Item 2", 'price' => '680', 'emoji' => '🍯', 'bg' => 'sand-400/25', 'rating' => 4.6, 'sold' => '739', 'slug' => 'food-and-gourmet-specialty-foods-and-international-cuisine-2'],
            ['category' => 'food-and-gourmet', 'subcategory' => 'specialty-foods-and-international-cuisine', 'name' => "Specialty Foods & International Cuisine — Sample Item 3", 'price' => '717', 'emoji' => '🍯', 'bg' => 'maroon-700/10', 'rating' => 4.8, 'sold' => '792', 'slug' => 'food-and-gourmet-specialty-foods-and-international-cuisine-3'],
            ['category' => 'food-and-gourmet', 'subcategory' => 'organic-and-health-foods', 'name' => "Organic and Health Foods — Sample Item 1", 'price' => '754', 'emoji' => '🍯', 'bg' => 'gold-500/15', 'rating' => 4.5, 'sold' => '845', 'slug' => 'food-and-gourmet-organic-and-health-foods-1'],
            ['category' => 'food-and-gourmet', 'subcategory' => 'organic-and-health-foods', 'name' => "Organic and Health Foods — Sample Item 2", 'price' => '791', 'emoji' => '🍯', 'bg' => 'sand-400/25', 'rating' => 4.7, 'sold' => '898', 'slug' => 'food-and-gourmet-organic-and-health-foods-2'],
            ['category' => 'food-and-gourmet', 'subcategory' => 'organic-and-health-foods', 'name' => "Organic and Health Foods — Sample Item 3", 'price' => '828', 'emoji' => '🍯', 'bg' => 'maroon-700/10', 'rating' => 4.9, 'sold' => '51', 'slug' => 'food-and-gourmet-organic-and-health-foods-3'],
            ['category' => 'food-and-gourmet', 'subcategory' => 'meal-kits-and-prepped-foods', 'name' => "Meal Kits & Prepped Foods — Sample Item 1", 'price' => '865', 'emoji' => '🍯', 'bg' => 'gold-500/15', 'rating' => 4.6, 'sold' => '104', 'slug' => 'food-and-gourmet-meal-kits-and-prepped-foods-1'],
            ['category' => 'food-and-gourmet', 'subcategory' => 'meal-kits-and-prepped-foods', 'name' => "Meal Kits & Prepped Foods — Sample Item 2", 'price' => '902', 'emoji' => '🍯', 'bg' => 'sand-400/25', 'rating' => 4.8, 'sold' => '157', 'slug' => 'food-and-gourmet-meal-kits-and-prepped-foods-2'],
            ['category' => 'food-and-gourmet', 'subcategory' => 'meal-kits-and-prepped-foods', 'name' => "Meal Kits & Prepped Foods — Sample Item 3", 'price' => '939', 'emoji' => '🍯', 'bg' => 'maroon-700/10', 'rating' => 4.5, 'sold' => '210', 'slug' => 'food-and-gourmet-meal-kits-and-prepped-foods-3'],

            // ---- Furniture & Office Equipment ----
            ['category' => 'furniture-and-office-equipment', 'subcategory' => 'office-desks-and-chairs', 'name' => "Office Desks & Chairs — Sample Item 1", 'price' => '236', 'emoji' => '🪑', 'bg' => 'gold-500/15', 'rating' => 4.7, 'sold' => '103', 'slug' => 'furniture-and-office-equipment-office-desks-and-chairs-1'],
            ['category' => 'furniture-and-office-equipment', 'subcategory' => 'office-desks-and-chairs', 'name' => "Office Desks & Chairs — Sample Item 2", 'price' => '273', 'emoji' => '🪑', 'bg' => 'sand-400/25', 'rating' => 4.9, 'sold' => '156', 'slug' => 'furniture-and-office-equipment-office-desks-and-chairs-2'],
            ['category' => 'furniture-and-office-equipment', 'subcategory' => 'office-desks-and-chairs', 'name' => "Office Desks & Chairs — Sample Item 3", 'price' => '310', 'emoji' => '🪑', 'bg' => 'maroon-700/10', 'rating' => 4.6, 'sold' => '209', 'slug' => 'furniture-and-office-equipment-office-desks-and-chairs-3'],
            ['category' => 'furniture-and-office-equipment', 'subcategory' => 'office-desks-and-chairs', 'name' => "Office Desks & Chairs — Sample Item 4", 'price' => '347', 'emoji' => '🪑', 'bg' => 'gold-500/15', 'rating' => 4.8, 'sold' => '262', 'slug' => 'furniture-and-office-equipment-office-desks-and-chairs-4'],
            ['category' => 'furniture-and-office-equipment', 'subcategory' => 'storage-cabinets-and-shelving', 'name' => "Storage Cabinets & Shelving — Sample Item 1", 'price' => '384', 'emoji' => '🪑', 'bg' => 'sand-400/25', 'rating' => 4.5, 'sold' => '315', 'slug' => 'furniture-and-office-equipment-storage-cabinets-and-shelving-1'],
            ['category' => 'furniture-and-office-equipment', 'subcategory' => 'storage-cabinets-and-shelving', 'name' => "Storage Cabinets & Shelving — Sample Item 2", 'price' => '421', 'emoji' => '🪑', 'bg' => 'maroon-700/10', 'rating' => 4.7, 'sold' => '368', 'slug' => 'furniture-and-office-equipment-storage-cabinets-and-shelving-2'],
            ['category' => 'furniture-and-office-equipment', 'subcategory' => 'storage-cabinets-and-shelving', 'name' => "Storage Cabinets & Shelving — Sample Item 3", 'price' => '458', 'emoji' => '🪑', 'bg' => 'gold-500/15', 'rating' => 4.9, 'sold' => '421', 'slug' => 'furniture-and-office-equipment-storage-cabinets-and-shelving-3'],
            ['category' => 'furniture-and-office-equipment', 'subcategory' => 'storage-cabinets-and-shelving', 'name' => "Storage Cabinets & Shelving — Sample Item 4", 'price' => '495', 'emoji' => '🪑', 'bg' => 'sand-400/25', 'rating' => 4.6, 'sold' => '474', 'slug' => 'furniture-and-office-equipment-storage-cabinets-and-shelving-4'],
            ['category' => 'furniture-and-office-equipment', 'subcategory' => 'conference-and-meeting-furniture', 'name' => "Conference & Meeting Furniture — Sample Item 1", 'price' => '532', 'emoji' => '🪑', 'bg' => 'maroon-700/10', 'rating' => 4.8, 'sold' => '527', 'slug' => 'furniture-and-office-equipment-conference-and-meeting-furniture-1'],
            ['category' => 'furniture-and-office-equipment', 'subcategory' => 'conference-and-meeting-furniture', 'name' => "Conference & Meeting Furniture — Sample Item 2", 'price' => '569', 'emoji' => '🪑', 'bg' => 'gold-500/15', 'rating' => 4.5, 'sold' => '580', 'slug' => 'furniture-and-office-equipment-conference-and-meeting-furniture-2'],
            ['category' => 'furniture-and-office-equipment', 'subcategory' => 'conference-and-meeting-furniture', 'name' => "Conference & Meeting Furniture — Sample Item 3", 'price' => '606', 'emoji' => '🪑', 'bg' => 'sand-400/25', 'rating' => 4.7, 'sold' => '633', 'slug' => 'furniture-and-office-equipment-conference-and-meeting-furniture-3'],
            ['category' => 'furniture-and-office-equipment', 'subcategory' => 'computer-tables-and-workstations', 'name' => "Computer Tables & Workstations — Sample Item 1", 'price' => '643', 'emoji' => '🪑', 'bg' => 'maroon-700/10', 'rating' => 4.9, 'sold' => '686', 'slug' => 'furniture-and-office-equipment-computer-tables-and-workstations-1'],
            ['category' => 'furniture-and-office-equipment', 'subcategory' => 'computer-tables-and-workstations', 'name' => "Computer Tables & Workstations — Sample Item 2", 'price' => '680', 'emoji' => '🪑', 'bg' => 'gold-500/15', 'rating' => 4.6, 'sold' => '739', 'slug' => 'furniture-and-office-equipment-computer-tables-and-workstations-2'],
            ['category' => 'furniture-and-office-equipment', 'subcategory' => 'computer-tables-and-workstations', 'name' => "Computer Tables & Workstations — Sample Item 3", 'price' => '717', 'emoji' => '🪑', 'bg' => 'sand-400/25', 'rating' => 4.8, 'sold' => '792', 'slug' => 'furniture-and-office-equipment-computer-tables-and-workstations-3'],
            ['category' => 'furniture-and-office-equipment', 'subcategory' => 'ergonomic-accessories', 'name' => "Ergonomic Accessories — Sample Item 1", 'price' => '754', 'emoji' => '🪑', 'bg' => 'maroon-700/10', 'rating' => 4.5, 'sold' => '845', 'slug' => 'furniture-and-office-equipment-ergonomic-accessories-1'],
            ['category' => 'furniture-and-office-equipment', 'subcategory' => 'ergonomic-accessories', 'name' => "Ergonomic Accessories — Sample Item 2", 'price' => '791', 'emoji' => '🪑', 'bg' => 'gold-500/15', 'rating' => 4.7, 'sold' => '898', 'slug' => 'furniture-and-office-equipment-ergonomic-accessories-2'],
            ['category' => 'furniture-and-office-equipment', 'subcategory' => 'ergonomic-accessories', 'name' => "Ergonomic Accessories — Sample Item 3", 'price' => '828', 'emoji' => '🪑', 'bg' => 'sand-400/25', 'rating' => 4.9, 'sold' => '51', 'slug' => 'furniture-and-office-equipment-ergonomic-accessories-3'],
            ['category' => 'furniture-and-office-equipment', 'subcategory' => 'office-lighting-and-fixtures', 'name' => "Office Lighting & Fixtures — Sample Item 1", 'price' => '865', 'emoji' => '🪑', 'bg' => 'maroon-700/10', 'rating' => 4.6, 'sold' => '104', 'slug' => 'furniture-and-office-equipment-office-lighting-and-fixtures-1'],
            ['category' => 'furniture-and-office-equipment', 'subcategory' => 'office-lighting-and-fixtures', 'name' => "Office Lighting & Fixtures — Sample Item 2", 'price' => '902', 'emoji' => '🪑', 'bg' => 'gold-500/15', 'rating' => 4.8, 'sold' => '157', 'slug' => 'furniture-and-office-equipment-office-lighting-and-fixtures-2'],
            ['category' => 'furniture-and-office-equipment', 'subcategory' => 'office-lighting-and-fixtures', 'name' => "Office Lighting & Fixtures — Sample Item 3", 'price' => '939', 'emoji' => '🪑', 'bg' => 'sand-400/25', 'rating' => 4.5, 'sold' => '210', 'slug' => 'furniture-and-office-equipment-office-lighting-and-fixtures-3'],

            // ---- Jewelry & Watches ----
            ['category' => 'jewelry-and-watches', 'subcategory' => 'necklaces-and-pendants', 'name' => "Necklaces & Pendants — Sample Item 1", 'price' => '236', 'emoji' => '💍', 'bg' => 'maroon-700/10', 'rating' => 4.7, 'sold' => '103', 'slug' => 'jewelry-and-watches-necklaces-and-pendants-1'],
            ['category' => 'jewelry-and-watches', 'subcategory' => 'necklaces-and-pendants', 'name' => "Necklaces & Pendants — Sample Item 2", 'price' => '273', 'emoji' => '💍', 'bg' => 'gold-500/15', 'rating' => 4.9, 'sold' => '156', 'slug' => 'jewelry-and-watches-necklaces-and-pendants-2'],
            ['category' => 'jewelry-and-watches', 'subcategory' => 'necklaces-and-pendants', 'name' => "Necklaces & Pendants — Sample Item 3", 'price' => '310', 'emoji' => '💍', 'bg' => 'sand-400/25', 'rating' => 4.6, 'sold' => '209', 'slug' => 'jewelry-and-watches-necklaces-and-pendants-3'],
            ['category' => 'jewelry-and-watches', 'subcategory' => 'necklaces-and-pendants', 'name' => "Necklaces & Pendants — Sample Item 4", 'price' => '347', 'emoji' => '💍', 'bg' => 'maroon-700/10', 'rating' => 4.8, 'sold' => '262', 'slug' => 'jewelry-and-watches-necklaces-and-pendants-4'],
            ['category' => 'jewelry-and-watches', 'subcategory' => 'rings-and-earrings', 'name' => "Rings & Earrings — Sample Item 1", 'price' => '384', 'emoji' => '💍', 'bg' => 'gold-500/15', 'rating' => 4.5, 'sold' => '315', 'slug' => 'jewelry-and-watches-rings-and-earrings-1'],
            ['category' => 'jewelry-and-watches', 'subcategory' => 'rings-and-earrings', 'name' => "Rings & Earrings — Sample Item 2", 'price' => '421', 'emoji' => '💍', 'bg' => 'sand-400/25', 'rating' => 4.7, 'sold' => '368', 'slug' => 'jewelry-and-watches-rings-and-earrings-2'],
            ['category' => 'jewelry-and-watches', 'subcategory' => 'rings-and-earrings', 'name' => "Rings & Earrings — Sample Item 3", 'price' => '458', 'emoji' => '💍', 'bg' => 'maroon-700/10', 'rating' => 4.9, 'sold' => '421', 'slug' => 'jewelry-and-watches-rings-and-earrings-3'],
            ['category' => 'jewelry-and-watches', 'subcategory' => 'rings-and-earrings', 'name' => "Rings & Earrings — Sample Item 4", 'price' => '495', 'emoji' => '💍', 'bg' => 'gold-500/15', 'rating' => 4.6, 'sold' => '474', 'slug' => 'jewelry-and-watches-rings-and-earrings-4'],
            ['category' => 'jewelry-and-watches', 'subcategory' => 'bracelets-and-bangles', 'name' => "Bracelets & Bangles — Sample Item 1", 'price' => '532', 'emoji' => '💍', 'bg' => 'sand-400/25', 'rating' => 4.8, 'sold' => '527', 'slug' => 'jewelry-and-watches-bracelets-and-bangles-1'],
            ['category' => 'jewelry-and-watches', 'subcategory' => 'bracelets-and-bangles', 'name' => "Bracelets & Bangles — Sample Item 2", 'price' => '569', 'emoji' => '💍', 'bg' => 'maroon-700/10', 'rating' => 4.5, 'sold' => '580', 'slug' => 'jewelry-and-watches-bracelets-and-bangles-2'],
            ['category' => 'jewelry-and-watches', 'subcategory' => 'bracelets-and-bangles', 'name' => "Bracelets & Bangles — Sample Item 3", 'price' => '606', 'emoji' => '💍', 'bg' => 'gold-500/15', 'rating' => 4.7, 'sold' => '633', 'slug' => 'jewelry-and-watches-bracelets-and-bangles-3'],
            ['category' => 'jewelry-and-watches', 'subcategory' => 'watches-for-men-and-women', 'name' => "Watches for Men & Women — Sample Item 1", 'price' => '643', 'emoji' => '💍', 'bg' => 'sand-400/25', 'rating' => 4.9, 'sold' => '686', 'slug' => 'jewelry-and-watches-watches-for-men-and-women-1'],
            ['category' => 'jewelry-and-watches', 'subcategory' => 'watches-for-men-and-women', 'name' => "Watches for Men & Women — Sample Item 2", 'price' => '680', 'emoji' => '💍', 'bg' => 'maroon-700/10', 'rating' => 4.6, 'sold' => '739', 'slug' => 'jewelry-and-watches-watches-for-men-and-women-2'],
            ['category' => 'jewelry-and-watches', 'subcategory' => 'watches-for-men-and-women', 'name' => "Watches for Men & Women — Sample Item 3", 'price' => '717', 'emoji' => '💍', 'bg' => 'gold-500/15', 'rating' => 4.8, 'sold' => '792', 'slug' => 'jewelry-and-watches-watches-for-men-and-women-3'],
            ['category' => 'jewelry-and-watches', 'subcategory' => 'fashion-jewelry', 'name' => "Fashion Jewelry — Sample Item 1", 'price' => '754', 'emoji' => '💍', 'bg' => 'sand-400/25', 'rating' => 4.5, 'sold' => '845', 'slug' => 'jewelry-and-watches-fashion-jewelry-1'],
            ['category' => 'jewelry-and-watches', 'subcategory' => 'fashion-jewelry', 'name' => "Fashion Jewelry — Sample Item 2", 'price' => '791', 'emoji' => '💍', 'bg' => 'maroon-700/10', 'rating' => 4.7, 'sold' => '898', 'slug' => 'jewelry-and-watches-fashion-jewelry-2'],
            ['category' => 'jewelry-and-watches', 'subcategory' => 'fashion-jewelry', 'name' => "Fashion Jewelry — Sample Item 3", 'price' => '828', 'emoji' => '💍', 'bg' => 'gold-500/15', 'rating' => 4.9, 'sold' => '51', 'slug' => 'jewelry-and-watches-fashion-jewelry-3'],
            ['category' => 'jewelry-and-watches', 'subcategory' => 'jewelry-storage-and-care', 'name' => "Jewelry Storage & Care — Sample Item 1", 'price' => '865', 'emoji' => '💍', 'bg' => 'sand-400/25', 'rating' => 4.6, 'sold' => '104', 'slug' => 'jewelry-and-watches-jewelry-storage-and-care-1'],
            ['category' => 'jewelry-and-watches', 'subcategory' => 'jewelry-storage-and-care', 'name' => "Jewelry Storage & Care — Sample Item 2", 'price' => '902', 'emoji' => '💍', 'bg' => 'maroon-700/10', 'rating' => 4.8, 'sold' => '157', 'slug' => 'jewelry-and-watches-jewelry-storage-and-care-2'],
            ['category' => 'jewelry-and-watches', 'subcategory' => 'jewelry-storage-and-care', 'name' => "Jewelry Storage & Care — Sample Item 3", 'price' => '939', 'emoji' => '💍', 'bg' => 'gold-500/15', 'rating' => 4.5, 'sold' => '210', 'slug' => 'jewelry-and-watches-jewelry-storage-and-care-3'],
        ];
    }

    /** Products belonging to one category (all its subcategories combined). */
    public static function forCategory(string $categorySlug): array
    {
        return array_values(array_filter(self::all(), fn ($p) => $p['category'] === $categorySlug));
    }

    /**
     * Searches product name + its category/subcategory names. Splits the query into
     * words and requires every word to appear somewhere in that combined text (in any
     * order) — so "office chairs" matches a product whose subcategory is literally
     * "Office Desks & Chairs" even though "office chairs" isn't a verbatim substring.
     * No database needed: this runs against the same static catalog the category pages use.
     */
    public static function search(string $query): array
    {
        $query = trim($query);
        if ($query === '') return [];

        $words = preg_split('/\s+/', mb_strtolower($query));
        $categories = BuyerCategories::all();

        return array_values(array_filter(self::all(), function ($product) use ($words, $categories) {
            $category = collect($categories)->firstWhere('slug', $product['category']);
            $subcategory = $category
                ? collect($category['subcategories'])->firstWhere('slug', $product['subcategory'])
                : null;

            $haystack = mb_strtolower(implode(' ', array_filter([
                $product['name'],
                $category['name'] ?? '',
                $subcategory['name'] ?? '',
            ])));

            foreach ($words as $word) {
                if (!str_contains($haystack, $word)) return false;
            }
            return true;
        }));
    }
}